### ISSUE TITLE
about call remote method by giving customized class as argument

### ISSUE THREAD

**Issue by yncxcw** [irmen/Pyro4#102]
I have problems by offer my customized class as argument to call remote,  but the remote did not show any sign that I have successfully did it.  Either I can't see any log out by 
export PYRO_LOGFILE=pyro.log
export PYRO_LOGLEVEL=DEBUG

Is the log output to a file or to the stdout ?   What I am supposed to do to make sending customized class work?

**Comment by irmen** [comment]
You'll have to be a lot more precise in describing what your problem is before you can get some useful help.  
- what OS are you on?
- what are you trying to do exactly (show a snippet of code)
- what behavior did you expect?
- what happened instead? 
- if you get an error, provide the exact error and traceback
- what does "sending customized class" mean exactly?

In the meantime:
yes, pyro logs to a *file* (default "pyro.log") unless you set it to ``{stderr}`` in which case the log output is written to the standard error output.
Read the manual about serializing classes (https://pythonhosted.org/Pyro4/clientcode.html#changing-the-way-your-custom-classes-are-de-serialized) and study the examples mentioned in that paragraph.

**Comment by yncxcw** [comment]
Hi, I am running Ubuntu 14.10, the code is like:

Class  A:

    id = ""

**Comment by yncxcw** [comment]
Hi, I am running Ubuntu 14.10, the code is like:

Class B:
       name=""
       list = []

       def __init__(self,name,list) : 
               self.name = name
               self.list   = list

Class A:
         id = ""
         keyValue={}

         b=None // is instance of class B

         def __init__(self, id , keyValue, b):
                 self.id = id
                 self.keyValue = keyValue
                 self.b = b


Client:
           
           a = A(id,keyValue,b)           // we construct a here
           proxy =  Pyro4.Proxy(url)
           proxy.call(a)                        // we call remote "call" by passing a as an argument which is a complicated class
 
 Server:
          
 class Server:

       def call(a): 
             print ("we get call from client and id is", a.id)


The problem is I can see the Client surely execute "proxy.call(a)", but the server did not print any thing.
However if I replace argument a some simple types(int, string), It will succeed and print something at server.  Moreover, I didn't get any error and traceback information. It's as if I didn't call remote call at all.

**Comment by irmen** [comment]
fix the basic things in your code first: the server code contains an error: in the definition of ``call`` is the ``self`` argument missing.  Your code as written above (formatting problems aside) should give you the following exception as well: ``TypeError: call() takes 1 positional argument but 2 were given``.  
If you're not getting that you're not posting the exact code you're running, or are doing something wrong elsewhere that you haven't shown us.
