### ISSUE TITLE
attribute example

### ISSUE THREAD

**Issue by tonyyherb** [irmen/Pyro4#105]
Hi! I am following the attribute example [https://github.com/irmen/Pyro4/blob/master/examples/attributes/](url)

I am wondering what's the meaning for this please? 
@Pyro4.expose
@property
    def prop_sub(self):
        return self.sub

I don't see the client code calling it and if i try to call `p.prop_value` in client code, it will cause an error:
> Pyro4.errors.SecurityError: refused to deserialize types with double underscores in their name: __main__.SubThingy

Is it possible to directly access nested object attribute in Pyro4? I saw some old docs here [https://pythonhosted.org/Pyro/7-features.html#nestedattrs](url) but couldn't find anything for Pyro4

**Comment by irmen** [comment]
Your link is a 404, you should probably have pasted [this one](https://github.com/irmen/Pyro4/tree/master/examples/attributes) instead.

The example is a little bit outdated it seems, sorry. Pyro4's security has been tightened a bit here and there and this particular code wasn't correctly updated to reflect this. I'll correct it.

The error though is sound, but unrelated to this example. Pyro4 is simply refusing to serialize the SubThingy object because it's module name has a double underscore in it and Pyro4 won't provide access to these kind of "private" modules or classes.

Then your question about nexted attribute access: [no that is not possible](https://pythonhosted.org/Pyro4/security.html#dotted-names-object-traversal) by design.

**Comment by tonyyherb** [comment]
Thanks for the quick fix! So I cannot have a class with variables being another class?

**Comment by irmen** [comment]
Sure you can. You just can't access members of it remotely via dotted notation, you'll have to write access methods on the containing class to do that.

**Comment by tonyyherb** [comment]
I see! It works. Thanks a lot for the help and clarification!
