### ISSUE TITLE
Keeping track of the number of connections to Pyro and killing them on the Pyro Server

### ISSUE THREAD

**Issue by mkmoisen** [irmen/Pyro4#108]
Hi Irmen,

In the [Best Practices section of the manual](https://pythonhosted.org/Pyro4/tipstricks.html#after-x-simultaneous-proxy-connections-pyro-seems-to-freeze-so-release-your-proxies-when-you-can), you mention the following:

> ‘After X simultaneous proxy connections, Pyro seems to freeze!’ So: Release your proxies when you can. A connected proxy that is unused takes up resources on the server. In the case of the threadpool server type, it locks up a single thread. If you have too many connected proxies at the same time, the server may run out of threads and stops responding... Still, it is a good thing to think about when you can release a proxy in your code...You can use explicit _pyroRelease calls or use the proxy from within a context manager.

I had a bug in my code, where I was opening up a connection in a loop and failing to close it, and this was causing Pyro to freeze. In this particular case, I couldn't open up a single connection outside of the loop to be used within, for reasons that I will not go into here. At any rate, I was able to track down the bug and fix it.

What I would like to do within the Pyro Server is to keep track of the number of opened connections and to kill them in round robin fashion (or even kill them all) if they exceed a certain number, and also log that this is happening so that my team becomes aware of a bug in their code. Would you be able to point me to a way to accomplish this?

I have the "client" code which our team uses as an interface to connect to the Pyro server, so all of our code interacts with the client when it wants to talk to Pyro server. All of the methods in the client code have decorators that will reconnect the session to the Pyro Server in the event that either the server or the NameServer restarts or closes in anyway, so this won't hurt anyone aside for the cost of reconnecting.

Best regards,

Matthew

**Comment by onnokort** [comment]
Let me just say: Seconded!

I just had a wild-goose-chase for a threading bug in my code. It out I simply got socket timeouts on Pyro objects simply due to all connection slots being full.

It would be really great if Pyro would either

- have an option (IMO preferably default-on) to kill lingering/old connections

- or, alternatively, have, for n configured, allowed simultaneous connections, another "(n+1)-slot", that will throw an error on the client side whenever it is accessed - to get a clean and informative heads up on what is going on.

Best regards,

Onno

**Comment by irmen** [comment]
The second suggestion is a nice idea that I haven't considered yet.

Still, issue #82  (perhaps combined with some way to not freeze up when the connection limit *is* reached) is really the thing to aim for I think

**Comment by irmen** [comment]
By the way @onnokort : you can already do this. Simply set COMMTIMEOUT in your server and it will close client connections that are idle for longer than the timeout.

**Comment by onnokort** [comment]
@irmen: Yes, that's a good point, but it is a bit of a blunt weapon: I had set a CONNTIMEOUT on _both_ the server and the client and I in my circumstances the connections on the server didn't timeout, but the timeout on the client triggered because the server's slot were full.

The 2nd approach would have the advantage of clearly indicating that there is a problem with full slots.

**Comment by irmen** [comment]
Yes, if your clients are actually still using all the proxies the server will never timeout on a connection and the slots will all remain taken.
I'm thinking about a good approach for reporting an error.  Ideally I don't want to do this immediately because it could be that another client leaves in the next few seconds, and we could take their worker. So maybe some sort of short timeout/retry here.

**Comment by irmen** [comment]
commits 92e555caa657f58d25726add75291b0d1ccbc626 and 8484209fec6aa5da6e7ab0df54fa29bff60ff00d implement the 2nd approach. Please have a look!
