### ISSUE TITLE
Unable to free server memory for large objects

### ISSUE THREAD

**Issue by rockg** [irmen/Pyro4#111]
I'm running into a memory issue on my server.  Essentially I have an object factory on the server that creates large objects (500MB or so) also on the server to be accessed by the client.  However, after the client disconnects the large proxy objects persist in the server's memory and I have not found a way to free it without terminating the server process.  The below gist contains the server code and the client code is below.  Running the client code results in a server process that becomes several GB and needs to be terminated.  Is there a way to free memory on the server objects when it's clear that they will not be needed so the server remains a reasonable size?  I tried `_pyroRelease` and that did not seem to do anything and I cannot use the context manager as the object is passed around by the client.

https://gist.github.com/rockg/3e3e18ccbe5b257c08c594a6555cf032

Client code:
```
from __future__ import print_function
import sys
import Pyro4

sys.excepthook=Pyro4.util.excepthook

def main():
    server = "localhost:60313"
    uri="PYRO:server@" + server
    creator = Pyro4.Proxy(uri)
    obj = creator.create()

if __name__=="__main__":
    main()
```

**Comment by irmen** [comment]
You're registering an object (instance) with the Pyro daemon, that contains a huge array.
Pyro will never release anything registered with the daemon, so that explains your memory that's not freed.

Either change your code to not leave large data referenced from your Pyro object (it can't be garbage collected this way!), or have a look at registering a *class* instead and choosing an appropriate instance mode that Pyro should use. 
See https://pythonhosted.org/Pyro4/servercode.html#pyro-daemon-publishing-pyro-objects and the ``instancemode`` example.

(I released this part is badly documented and made an issue #112 to improve this)

**Comment by rockg** [comment]
I played around with this and I think `session` will suit my needs, but is there a way to get the object garbage collected after the client disconnects?  The memory still sticks around even though the object should not be used again as the session is no longer there.  Is there a reason for it not to be collected?

**Comment by irmen** [comment]
It's simple really.
If you register an object, Pyro puts it into a registry in the daemon. Because it has no way of knowing when it's no longer needed, and because of Python's reference counting mechanism, it will sit there forever until you shutdown the daemon.
If you don't like this use the instancing mechanism I proposed - it's made for exactly issues such as this.
By the way: if you use ``session``, the object *will* get released as soon as the client disconnects. If you don't see the memory use decrease it is probably because of the way your OS reports process memory use, or the way Python itself allocates/deallocates memory. Try creating a standalone program without Pyro that allocates the big object and then releases it, and compare its behavior. If you still think Pyro's not releasing your object even when a non-Pyro program is, please report here again because that would be a bug.

**Comment by irmen** [comment]
Actually upon closer inspection it seems that the moment session instances are released could be improved a bit: the socket connection object is nicely closed but due to the way Python's __del__ methods work, the session objects from it might not be released immediately as well.

Hence reopening this.

**Comment by irmen** [comment]
Right, that was almost a oneliner  8922ae76af317e9eded5e0de49e6aad01ceb96aa

**Comment by rockg** [comment]
Yes, now the memory is released as expected.  Thank you.
