### ISSUE TITLE
 'NoneType' object has no attribute 'error'

### ISSUE THREAD

**Issue by weyou** [irmen/Pyro4#117]
Sometimes,  my code will get the exception:

```
Exception ignored in: <bound method SocketConnection.__del__ of <Pyro4.socketuti
l.SocketConnection object at 0x03A120A8>>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pyro4-4.44.dev0-py3.4.egg\Pyro4\socketutil
.py", line 437, in __del__
  File "C:\Python34\lib\site-packages\pyro4-4.44.dev0-py3.4.egg\Pyro4\socketutil
.py", line 448, in close
AttributeError: 'NoneType' object has no attribute 'error'
```

**Comment by irmen** [comment]
- does it also occur when you're using an officicial release version of Pyro instead of a development build
- can you give more context?  In what situation does it occur? It's a bit weird because it means the socket.error that the code references has been removed from under us.

That being said, the error seems rather harmless.
