### ISSUE TITLE
Expose class/method without changing the original code

### ISSUE THREAD

**Issue by weyou** [irmen/Pyro4#120]
The @expose is great and elegant solution to keep the Pyro object safe.  Except:

Previously, I can easily enable an exist object to be accessible from remote by register it with Pyro. This can be done without changing anything to the object code.  It's very convenient. In most case, the class definition module is from a standalone module(or I want it to be a standalone module).  It can be re-used without the Pyro installed. 

Now I must change the original code of the class definition to add the @expose decorator. The modified new module cannot be used if not install Pyro.

So it would be great if there is any other way to specify the exposed class/property/method list.  For example:
```
def register(self, obj_or_class, objectId=None, force=False, exposeMethods=None, exposeProperties=None):
     ....
```

**Comment by irmen** [comment]
I'm happy to report that it's already possible to do what you suggested!  :smiley: 

Up until Pyro version 4.46, it is *not necessary* to use ``@expose`` at all. Unless you set the config item REQUIRE_EXPOSE to True.

Now, starting with Pyro 4.46, it is set to True by default BUT you can choose to set it back to False if you so desire.  This makes Pyro still work as before where you don't have to use ``@expose``.

Better is to not change the config item but instead properly expose the class from the standalone module or the library. It may not be obvious but *this does not require you to change the code*  of that module or library to add ``@expose`` decorators to it.  Remember that a Python decorator is just a function returning a new function (or class). So it is possible to write something like this:

```python
class SomeClassFromLibrary(object):
    def method1(self):
        pass
    def method2(self):
        pass


ExposedClass = Pyro4.expose(instance_mode="percall")(SomeClassFromLibrary)

daemon.register(ExposedClass)
```

As you can see, it's even possible to configure the instance_mode if you so desire!
I'll add the above example to the documentation of ``@expose`` because I agree that the notion of having to change your standalone/library module's source code to use the classes with Pyro may be holding people back.

But IMO the best solution is to not register or return classes from (third party, or stand-alone) libraries or modules directly with Pyro but always to build an adapter class yourself where you are in full control over what is remotely accessible and what data travels over the wire.

**Comment by weyou** [comment]
Get it. Hope to see the example in the documentation to show how to expose class/property/method with expose function call.
Thanks again for your great work.

**Comment by irmen** [comment]
See commit 9465d23b2a676c981ea4b25c98d7b8c0c06043fa
