### ISSUE TITLE
Pyro4 version 4.38 not compatible with Python 2.6 anymore since serpent 1.14 released

### ISSUE THREAD

**Issue by laurentbristiel** [irmen/Pyro4#131]
We are using Pyro4 4.38 with Python 2.6.
According to the [changelogs](https://pythonhosted.org/Pyro4/changelog.html)  it should be Python 2.6 compatible, and it was until last night.
Pyro4 is using serpent with this [requirement line](https://github.com/irmen/Pyro4/blob/4.38/requirements.txt):
````
serpent>=1.11
````
but serpent 1.14 just got released and is [not supporting Python 2.6 anymore](https://github.com/irmen/Serpent/commit/ad04a1cc510697ed158f6e12c5e3030f527ef33e).
This breaks the Python 2.6 compatibility of Pyro4 version 4.38.

Should we set max version of serpent to 1.13 on the Pyro4 for the 4.38 tag?
````
serpent>= 1.11,<=1.13
````

**Comment by irmen** [comment]
It is true that the underlying serpent library was officially supported on python 2.6 until the previous release, and since 1.15 not anymore.

_This has been the case for Pyro4 itself for quite some time already._

Since Pyro4 version 4.39 in july last year, it has no longer been officially supported on python 2.6 (and 3.2).  If you're still using it with recent versions on python 2.6 and it works, it is pure coincidence.

Note that python 2.6 is no longer supported by the Python software foundation since _october 2013_   .

My suggestion is: stop using python 2.6 and start using 3.5 (or 2.7 if you must). 
Alternatively, pin your pyro4 version to an older version that still works on python 2.6.

**Comment by laurentbristiel** [comment]
We are using the version 4.38 of pyro4 because it still had the Python 2.6 support.
But anyway, I know you are right, time to move away from Python 2.6 ....
Thanks for your answer, and thanks for your great work on those libs!
