### ISSUE TITLE
source code string cannot contain null bytes? 

### ISSUE THREAD

**Issue by zxpatric** [irmen/Pyro4#152]
**To reproduce:**

Run main.py in  https://drive.google.com/open?id=0B185R70hbZHkUndrenNVZFhmdkk 

**Observation:**
if change 
        lf = open('./data/bad_left.pgm', 'rb')
        rf = open('./data/bad_right.pgm', 'rb')
to 
        lf = open('./data/good_left.pgm', 'rb')
        rf = open('./data/good_right.pgm', 'rb')

then it ran through fine. So the exception has something to do with picture content?

**Call stack:**
    pyroP.call("saveLeftRight", ldata, rdata)
	at net.razorvine.pyro.serializer.PyroExceptionSerpent.FromSerpentDict(PyroExceptionSerpent.java:32)
	at net.razorvine.pyro.serializer.SerpentSerializer$DictConverter.convert(SerpentSerializer.java:58)
	at net.razorvine.serpent.ObjectifyVisitor.visit(ObjectifyVisitor.java:69)
	at net.razorvine.serpent.ast.DictNode.accept(DictNode.java:8)
	at net.razorvine.serpent.ast.Ast.accept(Ast.java:51)
	at net.razorvine.serpent.ast.Ast.getData(Ast.java:45)
	at net.razorvine.pyro.serializer.SerpentSerializer.deserializeData(SerpentSerializer.java:47)
	at net.razorvine.pyro.PyroProxy.internal_call(PyroProxy.java:272)
	at net.razorvine.pyro.PyroProxy.call(PyroProxy.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)

net.razorvine.pyro.PyroException: net.razorvine.pyro.PyroException: [builtins.ValueError] source code string cannot contain null bytes

**Comment by irmen** [comment]
Seems like this is the response from your Pyro server, so the Pyrolite client is sending invalid serialized data. Which would be a bug in serpent.jar, when dealing with strings from Jython. I'll investigate.

offtopic: are you really sending uncompressed PGM files over the network? What a waste of bandwidth and cpu cycles.... the 2mb pgm files easily compress down to ~60kb jpegs 😉

**Comment by zxpatric** [comment]
Thanks for looking into it.  

Thought about the PGM to JPG thing but the clients require lossless images. Considering the lossless compression ratio of TIFF and PNG, I decided not to bother :)    

The ratio of compression for TIFF is around 2:1, for PNG is around 2,7:1 and for JPEG we obtained a compression ratio of 16:1. Lossless image representation formats. Greyscale image: This image is a greyscale image, each pixel is 8 bits.

**Comment by irmen** [comment]
Fair enough.   By the way a temporary workaround for the crash here is to convert your data (ldata and rdata I think) to ``bytearray`` first before calling the saveLeftRight method.  This does require the most recent serpent.jar

I'm still looking into the actual problem; it seems serializing str that contain \x00 is problematic.  (that's why the conversion to bytearray gets rid of the issue. (Unfortunately jython is 2.x level python and doesn't make a clear distinction between str and byte by itself, like python 3.x does)

**Comment by irmen** [comment]
This is a serpent issue so I'm closing this one here. See above for the new issue.

**Comment by irmen** [comment]
@zxpatric a new Serpent library has been released containing the fixes for the above problems. You can update this separately - no need to update Pyro and Pyrolite

**Comment by irmen** [comment]
@zxpatric  I'm sorry but the handling of unicode strings when using Jython is totally unreliable due to bug2008 in Jython. Hence I've again added a (better) check in serpent that will crash if it encounters a string that might be incorrectly decoded from the server.  Sending stuff *to* the server should still be okay
