### ISSUE TITLE
arguments for constructor of a class

### ISSUE THREAD

**Issue by eendebakpt** [irmen/Pyro4#161]
If I create a remote object, how can I pass arguments to the constructor? I would like to do something like:

```
...
daemon = Pyro4.Daemon()  
uri = daemon.register(myclass
ns = Pyro4.locateNS() 
ns.register('myclass', uri)) 
...
hm = Pyro4.Proxy("PYRONAME:myclass", argument1=10, argument2='test') 
```
The last line does not work. 

In the docs I found the term `instance_creator`, but I don't know whether this solves my issue (and if so, how).

**Comment by irmen** [comment]
you're creating a proxy there, not an actual instance of the remote object.
Pyro takes care of that for you depending on the mode you chose.
So yeah, that's why the instance_creator is there: to control *on the server* how your objects are constructed.
All other parameters from the client you'll have to pass via regular method calls. Nothing is stopping you from defining a normal "init" method of sorts that you can call instead. Make sure you're using single or per-session instance mode though, otherwise pyro creates a fresh object for you for every call.
See http://pythonhosted.org/Pyro4/servercode.html#controlling-instance-modes-and-instance-creation

**Comment by eendebakpt** [comment]
@irmen I solved the issue by creating a wrapper class (I have limited control over the class I want to use):
```
# on server
from xxxx import dummy

class modulestarter:
    def __init__(self):
        pass
    def start_module(self, *args, **kwargs):
        obj = dummy(*args, **kwargs)
        return obj

uri = daemon.register(dummy)
uri2 = daemon.register(modulestarted)

# in client
        xx = Pyro4.Proxy('PYRONAME:startmodule')
        remote_dummy=xx.start_module(name='test')

```
Are there any technical reasons for not including this kind of functionality in the Pyro framework?

**Comment by irmen** [comment]
There is nothing special going on here: you're simply defining a factory method ``start_module`` that creates a new object which is returned, in this case all the way back to the client. That's got nothing to do with Pyro - it is exactly the same code you would write in normal Python.  (you *are* aware that the ``obj`` you're returning, is passed *by value* and when you use it in your client code, it is not interacting with the server at all?)

There are two things related to object creation that Pyro has a play in:
- the creation of *pyro* objects in the sever, for that there is the functionality we already discussed above.
- the transparent proxying of *pyro* objects in the server that you create in your server code. For this, look up the 'autoproxy' feature and have a look at the 'shoppingcart' example.

The rest is just how normal Python code would work.
