### ISSUE TITLE
Local installation hangs on resolving serpent dependency

### ISSUE THREAD

**Issue by wonderg** [irmen/Pyro4#173]
If serpent is already installed
```
[root@host]# pip3.4 list | grep serpent
serpent (1.8)
```
And you try to install Pyro3.4 from source 

`setup3.4 setup.py install `

However, Pyro4 installation try to download serpent from pypi.python.org
```

Installed /usr/lib/python3.4/site-packages/Pyro4-4.59-py3.4.egg
Processing dependencies for Pyro4==4.59
Searching for serpent>=1.19
Reading https://pypi.python.org/simple/serpent/
```

And fails if host is not connected to public Internet.

**Comment by irmen** [comment]
It needs to download a newer version of Serpent than the one you have installed (1.19 is eleven releases newer than 1.8).  

Either connect to the internet so that the installer can do its work automatically, or install the proper serpent version yourself manually, and then re-run the pyro installer.
