### ISSUE TITLE
Projects using Pyro4

### ISSUE THREAD

**Issue by Peque** [irmen/Pyro4#182]
Would you be willing to add a section in the documentation (i.e.: in "Intro and Example") for "Projects using Pyro4"? If so, I would like to add [osBrain](https://osbrain.readthedocs.io/en/stable/) (have a look at it if you have some time and feel interested).

I guess you wouldn't like to have a single project there, but maybe you know about other use cases which you can display? Among those 350+ stars I bet there are a couple of interesting projects! Hopefully some are free software too.

I think it could be beneficial for both:

- You get to "show off" (if others use your project it usually means your project is cool).
- The other projects get some visibility.

**Comment by irmen** [comment]
It sounds like a nice idea but from my experience with the same in the Pyro 3.x documentation, it turned out to be tedious to maintain. 

I guess now that we have github it is easy for other projects to make a pullrequest to add their link to the list, but as it turns out only very few people are like you and actively contribute  🤔 

Personally, I haven't really kept a list of projects that use Pyro. Ofcourse I have talked to people in the past about it but I haven't kept notes about it so it's hard to build a list myself.

**Comment by irmen** [comment]
Closing this because I'm not able to put effort in this myself, sorry about that.

**Comment by Peque** [comment]
No problem. Thanks for considering it! :blush:
