### ISSUE TITLE
Cannot obtain remote traceback with seriliazed custom exceptions

### ISSUE THREAD

**Issue by nedo99** [irmen/Pyro4#201]
Hello,

Started using Pyro4 recently and run in the following issue.
In my code I need to raise a custom exception in remote object method. Of course I get an error saying that it is unknown unserializable object, even thought I inherit it from `Exception` class, which is serializable. Then I use `SerializerBase` to serialize my custom exception to be able to raise my custom exception. That works, but in that case `Pyro4.util.getPyroTraceback()` returns empty list. So basically remote traceback, the most important part, is missing.

Could you point me to solution for this use case? I see this as a major issue. How can I obtain remote traceback for custom exceptions?

Regards,
Nedim

**Comment by irmen** [comment]
> I get an error saying that it is unknown unserializable object, even thought I inherit it from Exception class, which is serializable.

Sure, that's because only the Exception part of your custom class is known to be serializable, it doesn't say anything about the specialization you've made in your own class. Hence the error. Actually, please confirm that this error is from your CLIENT program.   Pyro4/serpent is perfectly capable of *serializing* arbitrary exceptions. It's the client side that you have to teach about how to reconstruct the appropriate exception object because it is basically a custom class that is serialized into a generic form.


> So basically remote traceback, the most important part, is missing.

Then your serialization function isn't working correctly, it is forgetting to serialize the exception object's attributes.   But again, you probably shouldn't use a custom *serialization* function, it's the *deserialization* that you'll need on the receiving side

By the way, the remote traceback is pyggybacked on the exception object in a `_pyroTraceback` attribute.   See https://github.com/irmen/Pyro4/blob/master/src/Pyro4/core.py#L1560 and  https://github.com/irmen/Pyro4/blob/master/src/Pyro4/util.py#L55
So your converter function that you'll be registering in `SerializerBase.register_dict_to_class` will need to fetch this from the attributes dictionary it is passed, and stick it back onto that attribute on the exception object it will be returning.

**Comment by nedo99** [comment]
Hi,

Thanks for detailed answer. Now it looks much better. The issue was with my serialization of custom exception. After I removed it and used only deserialization I got the traceback.

Regards,
Nedim
