### ISSUE TITLE
pyro_port_range

### ISSUE THREAD

**Issue by adamf663** [irmen/Pyro4#211]
When a daemon is created without specifying a port number, a high numbered port is assigned.
However, I'm planning on running it behind a firewall and have to open up any ports used.
I intend to add some iptable rules to open up the nameserver port and a range of ports to use for daemons.
Is there a way to control the port range as was available in Pyro3's PYRO_PORT_RANGE?
I can hard code it when starting a daemon, but I'd rather it came from a pool.

**Comment by adamf663** [comment]
When a daemon is created without specifying a port number, a high numbered port is assigned.
However, I'm planning on running it behind a firewall and have to open up any ports used.
I intend to add some iptable rules to open up the nameserver port and a range of ports to use for daemons.
Is there a way to control the port range as was available in Pyro3's PYRO_PORT_RANGE?
I can hard code it when starting a daemon, but I'd rather it came from a pool.

**Comment by pevogam** [comment]
+1

I have had similar problems in the past so I am curious to see best practices about handling this as well which don't involve opening all ports.

**Comment by irmen** [comment]
This is by design. Pyro4 lets the operating system decide on a suitable port number (if you don't specify it yourself) which is much better than the often-working-but-sometimes-not attempt that Pyro3 did by trying to find a free port in a port range.

Essentially, if you're not happy with the OS's choice of a port number, you're responsible to specify it yourself. Pyro won't choose for you. 
This means you'll have to make a wrapper around the daemon if you want to allocate a dynamic port but in a specified range. The wrapper needs to select a port in the range, and keep track of the ports that it used for all the deamons that it spawned. I think a simple shell script or python launcher script could do this, incrementing an environment variable, and launching daemon's with their port number set to that environment variable. You could store it in /var perhaps or in ~/.config to persist it across multiple calls

**Comment by irmen** [comment]
Oh, you could even let the wrapper store the daemon's uri in the name server under a certain meta tag. It could then query the name server to check what port numbers it gave out
