### ISSUE TITLE
Expose parent(s) class(es) methods and descriptors

### ISSUE THREAD

**Issue by gst** [irmen/Pyro4#212]
Hi,

I realize that Pyro only exposes the class own methods & descriptors, not taking into account the parent(s) class(es) : 

python : 3.6

```
class Parent:
    def meth1(self):
        "not exposed"
    @property
    def prop1(self):
        "not exposed"

@Pyro4.expose
class Child(Parent):
    def meth2(self):
        "exposed"
    # etc..
```

would you consider a PR making the parent(s) class methods & descriptors also exposed ? (it's a one liner change) ; that would make Pyro usable in my use case.. otherwise I'm afraid it won't make my job.

Thank your for Pyro !

**Comment by irmen** [comment]
No, such a feature is not going to make it in this form into Pyro4.

It would fundamentally change the security model of exposed classes. Because Python doesn't have the concept of method access levels, it would be way to easy to expose methods to the outside world (from a base class) that should never be exposed.  It breaks Pyro's rule of "Pyro doesn’t allow remote access to anything of your class unless explicitly told to do so. ".

There are some ways to achieve what you want ofcourse. One way is to create an "external interface" class that contains the methods you want to expose, and delegate those to the methods of whatever class hierarchy it is defined as internally.

Another way is to disable the REQUIRE_EXPOSE config item. This will essentially open up every method and property of your Pyro classes to be remotely accessible (including the ones inherited from base class hierarchy). Be sure you realize what the security implications are of doing this.

**Comment by gst** [comment]
effectively REQUIRE_EXPOSE = False seems to make my job as well.

Thanks for the input. I'll use that for now.

otherwise I was thinking to a new "full_expose" decorator but that would allow this on a case per case basis..  what do you think about it ?

**Comment by irmen** [comment]
Not in the core of Pyro4 itself - no new features will be added.  

Perhaps in Pyro5 though, because the REQUIRE_EXPOSE flag is not present there anymore. I'm not convinced though. Why do you need this feature? Why can't it be solved with an external interface class?

Also I would prefer to make it really obvious from the name of the decorator what it is doing, so we should name it something like "expose_supers".

**Comment by gst** [comment]
I don't have necessarily control over the parent(s) class(es).. Then in that case I'd like to be able to still exposes their methods/properties

**Comment by irmen** [comment]
No need to have control over the parent classes:

    class Base:
        def base_method(self, arg):
            pass
    
    class Sub(Base):
        def sub_method(self, arg):
            pass
    
    
    class External(Sub):
        @expose
        def base(self, arg):
            return self.base_method(arg)
    
        @expose
        def sub(self, arg):
            return self.sub_method(arg)
