### ISSUE TITLE
get traceback on server side

### ISSUE THREAD

**Issue by gst** [irmen/Pyro4#215]
I would like to have the possibility to have remote tracebacks be logged by default - **on server side** - or with an option eventually.

basically all would be good if in function core.py:Daemon.handle_request() on line 1458:

`log.debug("Exception occurred while handling request: %r", xv)`

was changed to 

`log.exception("Exception occurred while handling request: %r", xv)`

would you consider this change, eventually keeping the current behavior but changing it with a new config item (say `config.SERVER_LOG_TRACEBACK` (if you have a better name ?) )?

**Comment by irmen** [comment]
Are you aware of the PYRO_LOGLEVEL (and PYRO_LOGFILE) environment variable settings? 
If you set PYRO_LOGLEVEL=DEBUG before starting your daemon, it will log those messages to the pyro.log file (or somewhere else if you set PYRO_LOGFILE).

As for the log level this message is logged at: it is not really an error as far as Pyro itself is concerned, when a method invoked by Pyro throws an exception. Pyro will intercept it and pass it back to the caller. That's why the log is done (by Pyro) on the rather modest debug setting.  Only warnings/errors in Pyro itself are logged on a higher log level.

I suppose if you really want to log exceptions thrown by your own server code, you'll have to simply add your own exception handler in the exposed method that logs it in the way you want.
