### ISSUE TITLE
distributed-computing2

### ISSUE THREAD

**Issue by ThailanHigor** [irmen/Pyro4#223]
I'm running the example "distributed-computing" and the time of single counter is less of multiple parallel counters. I can't understanding why.
I imagine that multiple counters is more fast than only one.
Anybody can help me and explain me this?

**Comment by irmen** [comment]
They should be, and this is the goal of this example.
How are you running this (OS, python version?) What is your exact output?
Here's mine:

```
$ python client.py                                         
(book text consists of 3735 lines total)
(artificial delays are used to dramatize the differences in execution time)

Counting the words using a single counter...
Top five words:
  said (462)
  alice (403)
  very (145)
  little (128)
  down (102)
Time taken: 3.85 sec.

Counting words using multiple parallel counters...
Top five words:
  said (462)
  alice (403)
  very (145)
  little (128)
  down (102)
Time taken: 0.47 sec.
```

**Comment by ThailanHigor** [comment]
I removed the artificial delay.
I'm using python 3.7 version and windows.

My output:

Counting the words using a single counter...
fop five words:
 said (462)
 alice (403)
 very (145)
 little (128)
 down (102)
Time taken: 4.61 sec.

Counting words using multiple parallel counters...
Top five wors:
 said (462)
 alice (403)
 very (145)
 little (128)
 down (102)
Time taken: 9.47 sec.

My execution:
Obs: In Portuguese.
![image](https://user-images.githubusercontent.com/32150270/69916223-300aea80-1437-11ea-941b-987ebe37f8e2.png)

**Comment by irmen** [comment]
Aha, you removed the artificial delay.  That is a significant change for this particular example. The problem is that the server of this example uses _threads_  to run multiple Pyro calls in parallel. And Python is not able to execute code in parallel in this way because of the GIT -- unless a thread is waiting on a signal or I/O. If you remove the artificial delay, most threads will now fight for access to the CPU... unfortunately.

I guess the explanation of the example (readme) should be more clear about this. I will update it.

Python's GIL is the cause of this and Pyro can't do anything about it unless you are doing actual _multiprocessing_  -- which is what the other distributed computing examples do correctly.
