### ISSUE TITLE
Support for python 3.9?

### ISSUE THREAD

**Issue by mjk4** [irmen/Pyro4#234]
Is it possible that support for python 3.9 can be added?  Hopefully it would be little more than adding changes to tox.ini, .travis.yaml and so on and hopefully no real code changes would be needed.

**Comment by irmen** [comment]
There are no problems using Pyro4 on Python 3.9. 

But yeah I guess we could add it to the test descriptor files.

**Comment by mjk4** [comment]
Thanks a lot, and such a fast response, too!  Do you know when it will be on PyPI?

**Comment by irmen** [comment]
@mjk4 is it really required to push a new version to PyPI? (is there a problem installing the current version in your python 3.9 project?)  Because so far there haven't been any actual code changes since the last release.

Usually I only push a new release version if it actually contains code changes that you need to have when you install the package.

**Comment by irmen** [comment]
btw, just pushed 4.81 to pypi
