### ISSUE TITLE
Allow SSL server sockets

### ISSUE THREAD

**Issue by alanjds** [irmen/Pyro4#49]
As in some PaaS contexts is a bit harder to set a SSH tunnel over, what about allowing an SSL socket?

Just asking before starting to hack, but what about plugging [ssl.wrap_socket](https://docs.python.org/2/library/ssl.html#ssl.wrap_socket) over [this `sock`](https://github.com/irmen/Pyro4/blob/master/src/Pyro4/socketutil.py#L298) via some argument switch?

Is this acceptable/desirable if I could provide a patch?

**Comment by divad** [comment]
Do you plan to add TLS support to Pyro4 still?

**Comment by irmen** [comment]
No, I don't have the incentive and expertise to do this myself.

**Comment by irmen** [comment]
Well, turns out that Python's ssl library has matured a bit since I last looked at it. It now does proper hostname verification etc. if you use a recent enough Python (2.7.9+ and 3.4.3+) .
I wanted to see if I could get a grasp of it and get it working in Pyro myself and it seems it works quite well in the latest master branch.

*TODO*:  
- docs
- testing with proper certs not only with the self-signed root certs that I created myself

**Comment by divad** [comment]
I recommend letsencrypt for testing with real certs.

**Comment by MatthewJohn** [comment]
Hey!

I implemented on an ssl implementation aaages ago that's been working in production ever since if you'd like to see any examples?

Thanks
Matt

Sent from my iPhone

On 4 Aug 2017, at 12:33, Irmen de Jong <notifications@github.com<mailto:notifications@github.com>> wrote:


Well, turns out that Python's ssl library has matured a bit since I last looked at it. It now does proper hostname verification etc. if you use a recent enough Python (2.7.9+ and 3.4.3+) .
I wanted to see if I could get a grasp of it and get it working in Pyro myself and it seems it works quite well in the latest master branch.

TODO:

  *   docs
  *   testing with proper certs not only with the self-signed root certs that I created myself

**Comment by MatthewJohn** [comment]
Please excuse me if it's actually already been implemented, I'm quite behind the times on this project :(

Sent from my iPhone

On 4 Aug 2017, at 12:59, David Bell <notifications@github.com<mailto:notifications@github.com>> wrote:


I recommend letsencrypt for testing with real certs.

**Comment by irmen** [comment]
@MatthewJohn yeah I committed it yesterday.
@divad I'll check them out

**Comment by irmen** [comment]
will let it remain in the oven for a little while longer but it seems that the new SSL support will land as I currently implemented it, into the next release 4.62
