### ISSUE TITLE
How to solve ProtocolError: invoke: reply sequence out of sync, got 0 expected 1???

### ISSUE THREAD

**Issue by ez47** [irmen/Pyro4#75]
I was doing some heavy polling on a host/server exposed method, then i used CTRL-C to exit the client which spawns the host/server via subprocess. Upon app reload i got that error, even after machine restart the error persists.

I assume the nameserver keeps state somewhere, where can i reset that state?

**Comment by irmen** [comment]
What you're seeing is Pyro's mechanism to prevent data corruption. 
It detected a mismatch in the request/reply cycle on the socket connection. This is usually caused by some form of abuse of the connection, such as reading from the same socket from multiple code paths.
Because Pyro contains a lock mechanism on the proxy, it can't be a threading issue. What your code does to trigger the connection abuse is unknown (you haven't shown any code). 
I suspect a problem in your code concerning sharing proxies over threads/processes. Don't do that. Give each concurrent code path their own proxy connection.
http://pythonhosted.org/Pyro4/clientcode.html#proxies-connections-threads-and-cleaning-up

**Comment by ez47** [comment]
Oke i figured out what went wrong, pyro4 and gevent dont work together, I had to disable socket monkeypatch to make it stop spewing that error, pretty much all RPC libraries use sockets and break with gevent it seems. Im trying to multiprocess + gevent by subprocessing python call with cpu affinity. no luck so far :(

steps to reproduce, save both files, run client.py

client.py
```
import subprocess, Pyro4, time

num_cpu         = 1
cpus            = [x for x in range(0, num_cpu)]
procs           = []

for cpu in cpus:
    proc        = { 
                    'cpu':cpu,
                    'thread':subprocess.Popen(["taskset", "-c", "{0},{1}".format(cpu , cpu+1), "python", "server_worker.py", str(cpu)], stdout=subprocess.PIPE),
                    'rpc':Pyro4.Proxy("PYRONAME:cpu{0}.FetcherRPC".format(cpu))
                  }
    
    
    print "HOST: CPU-{0} RPC INIT".format(cpu)
    proc['rpc'].fetch([])

    procs.append(proc)

alive = True
dead = []
while alive:
    for proc in procs:
        if proc['rpc'].alive():
            error_log = proc['rpc'].get_error_log()
            debug_log = proc['rpc'].get_debug_log()

            if error_log:
                print "CPU-{0} ERROR LOG: {1}".format(proc['cpu'], error_log)

            if debug_log:
                print "CPU-{0} DEBUG LOG: {1}".format(proc['cpu'], debug_log)


            time.sleep(1)
        else:
            print "proc dead?"
            dead.append(proc)

    if len(dead) == num_cpu:
        alive = False
        print "Completed All CPU Jobs"

```


server_worker.py
```
import Pyro4, sys, time

from gevent import monkey

Pyro4.config.REQUIRE_EXPOSE = True 
monkey.patch_all(thread=False) #without socket=False gives Protocol Error


class FetcherRPC(object):
    def __init__(self):
        self.debug_log = []
        self.error_log = []
        self._alive    = True
        self.jobs = []
        self.progress = 0
        
    @Pyro4.expose
    def alive(self):
        return self._alive


    def log_error(self, data):
        self.error_log.append(str(data))

    @Pyro4.expose
    def get_error_log(self):
        copy_log = self.error_log
        self.error_log = []

        return copy_log

    def log_debug(self, data):
        self.progress += 1
        self.debug_log.append('Progress:{0} {1}'.format(self.progress, data))

    @Pyro4.expose
    def get_debug_log(self):
        copy_log = self.debug_log
        self.debug_log = []

        return copy_log

    @Pyro4.expose
    @Pyro4.oneway
    def fetch(self, urls):
        while True:
            self.log_debug('TEST TEST TEST')
            time.sleep(0.3)


FRPC = FetcherRPC()
daemon=Pyro4.Daemon()                 # make a Pyro daemon
ns=Pyro4.locateNS()                   # find the name server
uri=daemon.register(FRPC, force=True)   # register the greeting object as a Pyro object
ns.register("cpu{0}.FetcherRPC".format(sys.argv[1]), uri)  # register the object with a name in the name server
daemon.requestLoop()

```

**Comment by irmen** [comment]
I don't know what gevent socket monkey patching does, but if it causes Pyro sequencing errors, it can't be a good thing. As I explained, these errors are thrown when the request/response pairs are off, which can only be caused by socket connections going haywire.

I don't understand your question about acquiring locks.

If this is a gevent thing, maybe this is not the right place to look for answers, perhaps it's better looking in the gevent corner of the room?
