### ISSUE TITLE
Flame oneway calls

### ISSUE THREAD

**Issue by jeremyherbert** [irmen/Pyro4#76]
Hi,

Is it possible to perform oneway calls using flame? I'm presently trying to digging through the code to try to find this.

My problem is that I am trying to run VTK remotely, and the calls return objects which are unable to be unpickled (the client is python3, which has no VTK port). I don't actually care about these return values as long as an exception has not occurred.

Right now I'm doing it with the following code (it works, but admittedly it is a terrible hack):

```
try:
    some_function_from_vtk()
except ImportError:
    pass
```

where `some_function_from_vtk` is a proxy to a remote function via flame.

Thanks,
Jeremy

**Comment by jeremyherbert** [comment]
PS: I just realised that there is a mailinglist for this project, sorry. But as github won't let me delete this issue, I will leave the question here.

**Comment by irmen** [comment]
You can't if you use Flame to access existing modules and builtins. If you use it to access your own modules you can use the oneway-decorator as usual, and it should work.

I don't know what VTK is.

I do think your current solution is better than calling the function as oneway, because now, you at least know the function has actually been called. If you mark it oneway you don't even know that for certain.
