### ISSUE TITLE
Frame calling builtins, module with hmac key configured

### ISSUE THREAD

**Issue by alexsilva** [irmen/Pyro4#77]
Frame does not support messages with the hmac key.

Frame starts a new proxy but does not pass the key:

https://github.com/irmen/Pyro4/blob/master/src/Pyro4/utils/flame.py#L102
https://github.com/irmen/Pyro4/blob/master/src/Pyro4/utils/flame.py#L69

The error occurs if I configure the hmac key
```
CommunicationError: cannot connect: hmac key config not symmetric
```

Example that generates the error:

```
import Pyro4

ns = Pyro4.locateNS(hmac_key='12345')
frame = Pyro4.Proxy(ns.lookup(Pyro4.constants.FLAME_NAME))

frame.builtin('max')([1,3,4,5])
```

But that fixes the problem:
```
import Pyro4

ns = Pyro4.locateNS(hmac_key='12345')

frame = Pyro4.Proxy(ns.lookup(Pyro4.constants.FLAME_NAME))

max = frame.builtin('max')
max.flameserver._pyroHmacKey = '12345' # <<<<<

max([1,3,4])

```

**Comment by irmen** [comment]
This is by design; it would be silly to send the server's hmac key to the client. The whole purpose of the hmac thing is that you have a symmetric secret so that you know the client is who he claims he is. 
If the (flame)server starts sending back its internally configured hmac key to the clients, all bets are off.

**Comment by alexsilva** [comment]
It would not send the server key to the client, but the client account key to itself.

```
import Pyro4

hmac_key= '12345'

ns = Pyro4.locateNS(hmac_key=hmac_key)

frame = Pyro4.Proxy(ns.lookup(
  Pyro4.constants.FLAME_NAME), 
  hmac_key=hmac_key
)

# frame hmac_key
max = frame.builtin('max')  # < hmac_key of frame 

max([1,3,4])
````

**Comment by alexsilva** [comment]
```
class FlameBuiltin(object):
    """Proxy to a remote builtin function."""

    def __init__(self, flameserver, builtin):
        # store a proxy to the flameserver regardless of autoproxy setting
        self.flameserver = Pyro4.core.Proxy(flameserver._pyroDaemon.uriFor(flameserver))
        
        # key hmac of client
        self.flameserver._pyroHmacKey = flameserver._pyroDaemon._pyroHmacKey

        self.builtin = builtin

    def __call__(self, *args, **kwargs):
        return self.flameserver.invokeBuiltin(self.builtin, args, kwargs)
```

Fails because the client did not pass the key

```
hmac_key = '12345'

ns = Pyro4.locateNS(hmac_key=hmac_key)

frame = Pyro4.Proxy(ns.lookup(Pyro4.constants.FLAME_NAME))
frame.builtin('max')

CommunicationError: cannot connect: hmac key config not symmetric
```

Now works (the key is passed around created proxy):

```
hmac_key = '12345'

ns = Pyro4.locateNS(hmac_key=hmac_key)

frame = Pyro4.Proxy(ns.lookup(Pyro4.constants.FLAME_NAME))
frame._pyroHmacKey = hmac_key 
frame.builtin('max')

CommunicationError: cannot connect: hmac key config not symmetric
```

Is there a security issue in the code or you do not want to change what you already have?

**Comment by irmen** [comment]
Calling flame.builtin(...) or flame.module(..) invokes a remote method on the flame server.
The Flame server class is unaware of any hmac key other than the one you configured on the daemon. That one is the server side secret, so we don't set it on the proxy that's created, because it would be transferred to the client. We don't want that to happen.

Now, you could perhaps argue that the client already is connected to the flame server with a correct hmac_key anyway (because otherwise how would it be able to invoke the remote methods?). Perhaps then we could, in this case, pre-set the hmac_key in the proxy that is returned. But I don't want to do this, on the priciple: "never send a hmac_key secret to a client".

This means that you explicitly have to set the hmac_key on any proxy your client code deals with (even if it got the proxy from the server). Yes, that is inconvenient maybe.  But right now I don't want to abandon the principle I mentioned.

**Comment by alexsilva** [comment]
Good explanation. I understand your thinking.
